language: node_js
node_js:
- 8.12.0
cache:
  yarn: true
install:
- yarn install
script:
- yarn lint
- yarn coverage
# - yarn codacy Commented out for now. Will enable again after Codacy processes the repo.
